const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#B8FF00",
    background: "#FAFAFA",
    foreground: "#0A0A0A",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    primary: "#B8FF00",
    primaryForeground: "#0A0A0A",
    secondary: "#F4F4F4",
    secondaryForeground: "#1A1A1A",
    muted: "#F0F0F0",
    mutedForeground: "#737373",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#10B981",
    warning: "#F59E0B",
    border: "#E5E5E5",
    input: "#E5E5E5",
  },
  dark: {
    text: "#FAFAFA",
    tint: "#B8FF00",
    background: "#000000",
    foreground: "#FAFAFA",
    card: "#0F0F0F",
    cardForeground: "#FAFAFA",
    primary: "#B8FF00",
    primaryForeground: "#0A0A0A",
    secondary: "#1A1A1A",
    secondaryForeground: "#FAFAFA",
    muted: "#1F1F1F",
    mutedForeground: "#A3A3A3",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#10B981",
    warning: "#F59E0B",
    border: "#1F1F1F",
    input: "#1F1F1F",
  },
  radius: 16,
};

export default colors;
